language: python
python:
  - "3.7"
  - "3.8"
dist: xenial
os: linux

before_script:
    - pip install -U -r requirements.txt

script:
    - pip3 check

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze-bots"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
